# ELK stack provisioning.
# vi: set ft=ansible :
# @author tenequm (Mykhaylo Kolesnik) (2017).
---
- hosts: all
  gather_facts: false

  tasks:
    - name: Installing Python 2.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

- hosts: elk

  roles:
    - tenequm.elk
